name: VSFFRTFFZFWDWCHP
on:
  schedule:
    - cron: '*/60 0,5,9,17,20 * * *'
  workflow_dispatch:
env:
   psnfqqrsfgbxbxsc:  ${{secrets.NTHVCBWFDHRDMWMX}}
   chxfrwprwfhjlhps:  ${{secrets.XSRBWXXWMSDWJZVG}}
   cxwnvmcjkzjfwfnn:  ${{secrets.XBWCKKCFKFDFMBGJ}}
   wvmqxmtcpkpxlmhg:  ${{secrets.LFPTTNCXBZQFKLSW}}
   kfbrhrdgntzzpmpt:  ${{secrets.DNQGJNKZGXLTRTMM}}
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
    - name: 'psnfqqrsfgbxbxsc'
      uses: PabloLec/website-to-gif@1.0.4
      with:
        url: ${{ env.psnfqqrsfgbxbxsc }}
        scroll_step: 50
        time_per_frame: 1
    - name: 'chxfrwprwfhjlhps'
      uses: PabloLec/website-to-gif@1.0.4
      with:
        url: ${{ env.chxfrwprwfhjlhps }}
        scroll_step: 50
        time_per_frame: 1
    - name: 'cxwnvmcjkzjfwfnn'
      uses: PabloLec/website-to-gif@1.0.4
      with:
        url: ${{ env.cxwnvmcjkzjfwfnn }}
        scroll_step: 50
        time_per_frame: 1
    - name: 'wvmqxmtcpkpxlmhg'
      uses: PabloLec/website-to-gif@1.0.4
      with:
        url: ${{ env.wvmqxmtcpkpxlmhg }}
        scroll_step: 50
        time_per_frame: 1
    - name: 'kfbrhrdgntzzpmpt'
      uses: PabloLec/website-to-gif@1.0.4
      with:
        url: ${{ env.kfbrhrdgntzzpmpt }}
        scroll_step: 50
        time_per_frame: 1
